### ISSUE TITLE
pass admin

### ISSUE THREAD

**Issue by myarfa** [Syauqizaidan/Learnify#1]
password admin???

**Comment by Syauqizaidan** [comment]
username : admin@gmail.com
password : admin

**Comment by Syauqizaidan** [comment]
login nya di learnify/welcome/admin ya. jangan di user login.

**Comment by Syauqizaidan** [comment]
admin@Gmail.com
admin

Pada tanggal Kam, 2 Apr 2020 pukul 19.13 myarfa <notifications@github.com>
menulis:

**Comment by aliashari57** [comment]
maaf tampilan yg muncul setelah login
404 page not found
