### ISSUE TITLE
Penamaan Berkas Tidak Sesuai dengan Konvensi di CodeIgniter 3

### ISSUE THREAD

**Issue by msazzuhair** [Syauqizaidan/Learnify#3]
**Describe the bug**
Penamaan beberapa berkas Controller dan Model tidak sesuai dengan konvensi di CodeIgniter 3.
Keterangan: [CodeIgniter ver 3.0.0 changelog](https://codeigniter.com/userguide3/changelog.html#version-3-0-0) 
Akibatnya, beberapa berkas tersebut tidak dapat diakses terutama di Linux atau OS sejenisnya.

**To Reproduce**
Steps to reproduce the behavior on Linux:
1. Akses ke laman admin, guru, atau materi

**Expected behavior**
Berkas-berkas tersebut seharusnya dapat diakses.

**Screenshots**
Controller error
![image](https://user-images.githubusercontent.com/15320135/85641562-1f62e000-b6b9-11ea-9c62-27d6408e5aa2.png)

Model error
![image](https://user-images.githubusercontent.com/15320135/85641606-40c3cc00-b6b9-11ea-9ec8-91cd346f0077.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome, Firefox
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -
 - Version: -

**Perbaikan**
Perbaikan dapat dilakukan dengan mengubah karakter awal pada nama berkas menjadi kapital/uppercase

**Comment by Syauqizaidan** [comment]
Halloo! 
Terima kasih sudah melaporkan bug ini, kebetulan aku lagi diluar nih. Kamu bisa bantu aku gak solve bugnya? Dengan cara pull request ke repo ini. 
Terima kasih yaaa

**Comment by Syauqizaidan** [comment]
Thanks ya @msazzuhair sudah membantu! 
Ditunggu laporan issues selanjutnya! ❤
